/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Igu;

/**
 *
 * @author Caro
 */
public class FrmPrincipal extends javax.swing.JFrame {

    DlgAniadirProducto formularioAniadir = new DlgAniadirProducto(this, true);
    
    
    public FrmPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MnuPrincipal = new javax.swing.JMenuBar();
        MnuVerListas = new javax.swing.JMenu();
        mnuAniadir = new javax.swing.JMenu();
        MnuAniadirLista = new javax.swing.JMenuItem();
        mnuAniadirProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Compras");
        setName("framePrincipal"); // NOI18N
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        MnuVerListas.setText("Ver listas");
        MnuPrincipal.add(MnuVerListas);

        mnuAniadir.setText("Añadir");

        MnuAniadirLista.setText("Llista");
        mnuAniadir.add(MnuAniadirLista);

        mnuAniadirProducto.setText("Producto");
        mnuAniadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAniadirProductoActionPerformed(evt);
            }
        });
        mnuAniadir.add(mnuAniadirProducto);

        MnuPrincipal.add(mnuAniadir);

        setJMenuBar(MnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAniadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAniadirProductoActionPerformed
        //creo y muestro la ventana para añadir un nuevo producto
        formularioAniadir.setLocationRelativeTo(this);
        formularioAniadir.setVisible(true);
        
    }//GEN-LAST:event_mnuAniadirProductoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuAniadirLista;
    private javax.swing.JMenuBar MnuPrincipal;
    private javax.swing.JMenu MnuVerListas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuAniadir;
    private javax.swing.JMenuItem mnuAniadirProducto;
    // End of variables declaration//GEN-END:variables
}
